<?php

declare(strict_types=1);

namespace App\Domain\Master\Fixture;

use Faker\Factory;
use Faker\Generator;
use App\Domain\User\Entity\User;
use App\Domain\Master\Entity\Master;
use App\Domain\Master\Entity\MasterProfile;
use App\Domain\Shared\ValueObject\Email;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class MasterFixtures extends Fixture
{
    public const TOTAL_MASTERS = 1;

    private Generator $faker;

    public function __construct(
        private readonly UserPasswordHasherInterface $passwordHasher
    ) {
        $this->faker = Factory::create('en_EN');
    }

    public function load(ObjectManager $manager): void
    {
        for ($i = 0; $i < self::TOTAL_MASTERS; $i++) {
            $master = $this->createMaster(
                $manager
            );

            // Store references for first 5 masters
            if ($i < self::TOTAL_MASTERS) {
                $this->addReference("master_{$i}", $master);
            }
        }

        $manager->flush();
    }

    private function createMaster(ObjectManager $manager): Master {
        $nickname = $this->faker->firstName();

        $normalizedNickName = $this->sanitizeForEmail($nickname);
        $email = strtolower('master' . '@webmaster.com');

        // Check if exists
        $repo = $manager->getRepository(User::class);
        $user = $repo->findOneBy(['email' => $email]);
        if (! $user) {
            // Create User
            $user = User::createMaster(
                id: 0, // Auto-generated by Doctrine
                email: Email::fromString($email),
                nickname: $normalizedNickName,
                password: 'temp',
                createdByUserId: 1 // System/Master user
            );

            $hashedPassword = $this->passwordHasher->hashPassword($user, 'Pass12B4?');
            $user->updatePassword($hashedPassword);

            $manager->persist($user);
            $manager->flush(); // Flush to get auto-generated ID
        }

        $userId = $user->getId();
        if (! $userId) {
            throw new \RuntimeException("User ID not generated for {$email}");
        }

        // Create Master
        $repo = $manager->getRepository(Master::class);
        $master = $repo->findOneBy(['user' => $userId]);
        if (! $master) {
            $master = new Master();
            $master->setUser($user);
            $master->setIsActive(true);
            $master->setIsBanned(false);

            $manager->persist($master);
            $manager->flush(); // Flush to generate master ID and UUID

            // Create Master Profile
            $profile = MasterProfile::create(
                master: $master,
                nickname: $nickname
            );

            $manager->persist($profile);
            $manager->flush();
        }

        return $master;
    }

    /**
     * Sanitize string for email (remove accents, spaces, special chars)
     */
    private function sanitizeForEmail(string $string): string
    {
        // Remove accents using transliteration
        $string = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $string);

        // Remove anything that's not alphanumeric
        $string = preg_replace('/[^a-zA-Z0-9]/', '', $string);

        return $string ?? '';
    }
}
