<?php

declare(strict_types=1);

namespace App\Application\User\Command;

use App\Domain\Employee\Entity\Employee;
use App\Domain\Employee\Entity\EmployeeProfile;
use App\Domain\Employee\Repository\EmployeeProfileRepositoryInterface;
use App\Domain\Employee\Repository\EmployeeRepositoryInterface;
use App\Domain\Shared\Exception\ValidationException;
use App\Domain\Shared\ValueObject\Email;
use App\Domain\User\Entity\User;
use App\Domain\User\Repository\UserRepositoryInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

final readonly class RegisterEmployeeHandler
{
    public function __construct(
        private UserRepositoryInterface $userRepository,
        private EmployeeRepositoryInterface $employeeRepository,
        private EmployeeProfileRepositoryInterface $employeeProfileRepository,
        private UserPasswordHasherInterface $passwordHasher
    ) {}

    public function __invoke(RegisterEmployeeCommand $command): int
    {
        // Validation
        $email = Email::fromString($command->email);
        //$nickname = $command->nickname;

        if ($this->userRepository->existsByEmail($email)) {
            throw new ValidationException('Email already exists.');
        }

        /* if ($this->employeeProfileRepository->existsByNickname($nickname)) {
            throw new ValidationException('Nickname already exists.');
        } */

        // Create User with auto-generated ID
        $tempUser = User::createEmployee(
            id: 0, // Will be auto-generated by Doctrine
            email: $email,
            password: 'temp',
            nickname: null,
            createdByUserId: $command->createdByUserId
        );

        $hashedPassword = $this->passwordHasher->hashPassword($tempUser, $command->password);

        $user = User::createEmployee(
            id: 0,
            email: $email,
            password: $hashedPassword,
            nickname: null,
            createdByUserId: $command->createdByUserId
        );

        $this->userRepository->save($user);
        $this->userRepository->flush(); // Flush to get auto-generated ID

        $userId = $user->getId();
        if (! $userId) {
            throw new \RuntimeException('User ID was not generated after persist');
        }

        // Create Employee entity
        $employee = new Employee();
        $employee->setUser($user);
        $employee->setIsActive(true); // New employees are active by default

        // Set office information if provided
        if ($command->department) {
            $employee->setDepartment($command->department);
        }
        if ($command->geoRegion) {
            $employee->setJob($command->job);
        }

        // Set geographic information if provided
        if ($command->geoCountry) {
            $employee->setGeoCountry($command->geoCountry);
        }
        if ($command->geoRegion) {
            $employee->setGeoRegion($command->geoRegion);
        }
        if ($command->geoState) {
            $employee->setGeoState($command->geoState);
        }
        if ($command->geoDistrict) {
            $employee->setGeoDistrict($command->geoDistrict);
        }
        if ($command->geoCity) {
            $employee->setGeoCity($command->geoCity);
        }

        $this->employeeRepository->save($employee);
        $this->employeeRepository->flush();

        // Create Employee Profile
        $birthDate = $command->birthDate
            ? new \DateTimeImmutable($command->birthDate)
            : null;

        $employeeProfile = EmployeeProfile::create(
            userId: $userId,
            //nickname: $nickname,
            name: $command->name,
            surname: $command->surname,
            birthDate: $birthDate,
            emailSecondary: $command->emailSecondary ?? null,
            phone: $command->phone ?? null,
            mobile: $command->mobile ?? null
        );

        $this->employeeProfileRepository->save($employeeProfile);
        $this->employeeProfileRepository->flush();

        return $userId;
    }
}
