<?php

declare(strict_types=1);

namespace App\Application\User\Command;

use App\Domain\Admin\Entity\Admin;
use App\Domain\Admin\Entity\AdminProfile;
use App\Domain\Admin\Repository\AdminRepositoryInterface;
use App\Domain\Admin\Repository\AdminProfileRepositoryInterface;
use App\Domain\Shared\Exception\ValidationException;
use App\Domain\Shared\ValueObject\Email;
use App\Domain\User\Entity\User;
use App\Domain\User\Repository\UserRepositoryInterface;
use App\Domain\User\ValueObject\UserRole;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

final readonly class RegisterAdminHandler
{
    public function __construct(
        private UserRepositoryInterface $userRepository,
        private AdminRepositoryInterface $adminRepository,
        private AdminProfileRepositoryInterface $adminProfileRepository,
        private UserPasswordHasherInterface $passwordHasher
    ) {}

    public function __invoke(RegisterAdminCommand $command): int
    {
        // Validation
        $email = Email::fromString($command->email);
        $nickname = $command->nickname;

        if ($this->userRepository->existsByEmail($email)) {
            throw new ValidationException('Email already exists.');
        }

        if ($this->adminProfileRepository->existsByNickname($nickname)) {
            throw new ValidationException('Nickname already exists.');
        }

        // Create User with auto-generated ID
        $tempUser = User::createAdmin(
            id: 0, // Will be auto-generated by Doctrine
            email: $email,
            password: 'temp',
            nickname: $nickname,
            createdByUserId: $command->createdByUserId
        );

        $hashedPassword = $this->passwordHasher->hashPassword($tempUser, $command->password);

        $user = User::createAdmin(
            id: 0,
            email: $email,
            password: $hashedPassword,
            nickname: $nickname,
            createdByUserId: $command->createdByUserId
        );

        $this->userRepository->save($user);
        $this->userRepository->flush(); // Flush to get auto-generated ID

        $userId = $user->getId();
        if (! $userId) {
            throw new \RuntimeException('User ID was not generated after persist');
        }

        // Create Admin entity
        $admin = new Admin();
        $admin->setUser($user);
        $admin->setIsActive(true); // New admins are active by default

        $this->adminRepository->save($admin);
        $this->adminRepository->flush();

        $adminProfile = AdminProfile::create(
            admin: $admin,
            nickname: $nickname
        );

        $this->adminProfileRepository->save($adminProfile);
        $this->adminProfileRepository->flush();

        return $userId;
    }
}
