<?php

declare(strict_types=1);

namespace App\Application\User\Command;

use App\Domain\User\Entity\User;
use App\Domain\Master\Entity\Master;
use App\Domain\Shared\ValueObject\Email;
use App\Domain\User\ValueObject\UserRole;
use App\Domain\Master\Entity\MasterProfile;
use App\Domain\Shared\Exception\ValidationException;
use App\Domain\User\Repository\UserRepositoryInterface;
use App\Domain\Master\Repository\MasterRepositoryInterface;
use App\Domain\Master\Repository\MasterProfileRepositoryInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

final readonly class RegisterMasterHandler
{
    public function __construct(
        private UserRepositoryInterface $userRepository,
        private MasterRepositoryInterface $masterRepository,
        private MasterProfileRepositoryInterface $masterProfileRepository,
        private UserPasswordHasherInterface $passwordHasher
    ) {}

    public function __invoke(RegisterMasterCommand $command): int
    {
        // Validation
        $email = Email::fromString($command->email);
        $nickname = $command->nickname;

        if ($this->userRepository->existsByEmail($email)) {
            throw new ValidationException('Email already exists.');
        }

        if ($this->masterProfileRepository->existsByNickname($nickname)) {
            throw new ValidationException('Nickname already exists.');
        }

        // Create User with auto-generated ID
        $tempUser = User::createMaster(
            id: 0, // Will be auto-generated by Doctrine
            email: $email,
            password: 'temp',
            nickname: $nickname,
            createdByUserId: $command->createdByUserId
        );

        $hashedPassword = $this->passwordHasher->hashPassword($tempUser, $command->password);

        $user = User::createMaster(
            id: 0,
            email: $email,
            password: $hashedPassword,
            nickname: $nickname,
            createdByUserId: $command->createdByUserId
        );

        $this->userRepository->save($user);
        $this->userRepository->flush(); // Flush to get auto-generated ID

        $userId = $user->getId();
        if (! $userId) {
            throw new \RuntimeException('User ID was not generated after persist');
        }

        // Create Master entity
        $master = new Master();
        $master->setUser($user);
        $master->setIsActive(true); // New admins are active by default

        $this->masterRepository->save($master);
        $this->masterRepository->flush();

        $masterProfile = MasterProfile::create(
            master: $master,
            nickname: $nickname
        );

        $this->masterProfileRepository->save($masterProfile);
        $this->masterProfileRepository->flush();

        return $userId;
    }
}
